apiVersion: apps/v1
kind: Deployment
metadata:
  name: cse-undergrad-gp-manage-deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cse-undergrad-gp-manage
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cse-undergrad-gp-manage
    spec:
      containers:
      - image: scgskku/cse-undergrad-gp-manage
        imagePullPolicy: Always
        name: cse-undergrad-gp-manage
        ports:
        - containerPort: 8091
        envFrom:
        - secretRef:
            name: cse-undergrad-gp-manage-secret