apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cse-undergrad-gp-manage-prod
resources:
- namespace.yaml
- secret.yaml
- deployment.yaml
- ingress.yaml
- service.yaml
images:
- name: scgskku/cse-undergrad-gp-manage
  newTag: 72c43b5a840f5b8cbe2373b3449081ffc44a8fa9
