apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cse-undergrad-gp-manage-prod
resources:
- namespace.yaml
- secret.yaml
- deployment.yaml
- ingress.yaml
- service.yaml
images:
- name: scgskku/cse-undergrad-gp-manage
  newTag: 9437a28ab8f43e7a9d669cf81f237916cbf67346
