apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mochimochi-obinox-discord-bot
resources:
- namespace.yaml
- secret.yaml
- deployment.yaml
images:
- name: obinox/mochimochi
  newTag: c6768e3afc8001193aae9e2461456d99e3ede3c9
