apiVersion: v1
kind: Secret
metadata:
  name: cse-undergrad-gp-manage-secret
type: Opaque
data:
  SESSION_SECRET: <path:kv/data/cse-undergrad-gp-manage-config#session-secret | base64encode>
  PORT: <path:kv/data/cse-undergrad-gp-manage-config#port | base64encode>
  DB_HOST: <path:kv/data/cse-undergrad-gp-manage-config#db-host | base64encode>
  DB_PORT: <path:kv/data/cse-undergrad-gp-manage-config#db-port | base64encode>
  DB_USERNAME: <path:kv/data/cse-undergrad-gp-manage-config#db-username | base64encode>
  DB_PASSWORD: <path:kv/data/cse-undergrad-gp-manage-config#db-password | base64encode>
  DB_DATABASE: <path:kv/data/cse-undergrad-gp-manage-config#db-database | base64encode>
  DB_DIALECT: <path:kv/data/cse-undergrad-gp-manage-config#db-dialect | base64encode>
  DB_TIMEZONE: <path:kv/data/cse-undergrad-gp-manage-config#db-timezone | base64encode>
  DB_LOGGING: <path:kv/data/cse-undergrad-gp-manage-config#db-logging | base64encode>
  DB_CONNECT_TIMEOUT: <path:kv/data/cse-undergrad-gp-manage-config#db-connect-timeout | base64encode>
  CSSYS_UPLOAD_PATH: <path:kv/data/cse-undergrad-gp-manage-config#cssys-upload-path | base64encode>
  CSSYS_PERMIT_STUDENT_COUNT: <path:kv/data/cse-undergrad-gp-manage-config#cssys-permit-student-count| base64encode>
  CSSYS_PERMIT_STUDENT_COUNT_SEMICON: <path:kv/data/cse-undergrad-gp-manage-config#cssys-permit-student-count-semicon | base64encode>
  MINIO_ENDPOINT: <path:kv/data/minio#MINIO_END_POINT | base64encode>
  MINIO_PORT: <path:kv/data/minio#MINIO_PORT | base64encode>
  MINIO_ACCESS_KEY: <path:kv/data/minio#MINIO_ACCESS_KEY | base64encode>
  MINIO_SECRET_KEY: <path:kv/data/minio#MINIO_SECRET_KEY | base64encode>
  MINIO_BUCKET: <path:kv/data/cse-undergrad-gp-manage-config#minio-bucket | base64encode>
