apiVersion: v1
kind: Secret
metadata:
  name: mochimochi-obinox-discord-bot-secret
type: Opaque
data:
  DISCORD_TOKEN: <path:kv/data/mochimochi-obinox#DISCORD_TOKEN | base64encode>
  CLIENT_ID: <path:kv/data/mochimochi-obinox#CLIENT_ID | base64encode>
  GUILD_ID: <path:kv/data/mochimochi-obinox#GUILD_ID | base64encode>
